### ISSUE TITLE
Stuck on scraping proxies

### ISSUE THREAD

**Issue by edgenull** [Xvirus0/Xvirus-Tools#9] opened 2023-05-14 18:07 UTC
Stuck on scraping proxies

1. Install as normal
2. Run start.bat - will be stuck on scraping proxies

**Expected behavior**
Should start the program.

**Screenshots**
![image](https://github.com/Xvirus0/Xvirus-Tools/assets/130695190/19c25722-0ba9-4ef2-bee4-4463332bc335)

**Desktop:**
 - OS: Windows 10
 - Version Latest

**Comment by DXVVAY** [comment] 2023-05-14 18:10
huh i thought i had fixed that the code runs perfectly for me it has happened to @Cwackz  once tho im not sure if thats fixed now lemmie see what i can do

**Comment by DXVVAY** [comment] 2023-05-14 18:26
@edgenull  update and try it now it should work now

**Comment by DXVVAY** [comment] 2023-05-15 06:31
Is it fixed?

**Comment by edgenull** [comment] 2023-05-15 17:30
Yep, it loads normally now, though while scraping proxies, it will show an error for about 0.2 seconds.
It doesn't ruin any functionality, but might be useful to fix.

I had to be quick to catch it, so here it is:

![image](https://github.com/Xvirus0/Xvirus-Tools/assets/130695190/0f0aec7b-cb61-45d5-98a0-07bdb00f10ab)

**Comment by edgenull** [comment] 2023-05-15 17:32
The proxy scraper gives me the following error (not the one when starting, but the 23rd tool):

![image](https://github.com/Xvirus0/Xvirus-Tools/assets/130695190/bf079a11-89ff-427a-bbda-d227aa0cfc96)

**Comment by edgenull** [comment] 2023-05-15 17:33
and if that wasn't enough, here's another error when trying to run "ai":

![image](https://github.com/Xvirus0/Xvirus-Tools/assets/130695190/295da564-5c42-44f8-ac8a-7af279934a13)

**Comment by DXVVAY** [comment] 2023-05-15 18:49
Yea ai is still a wip i found out about yesterday

**Comment by Cwackz** [comment] 2023-05-15 19:59
> and if that wasn't enough, here's another error when trying to run "ai":
> 
> ![image](https://user-images.githubusercontent.com/130695190/238425791-295da564-5c42-44f8-ac8a-7af279934a13.png)

I'll look into the issue with in a moment, i think i know what the issue is.

**Comment by Cwackz** [comment] 2023-05-15 20:12
> and if that wasn't enough, here's another error when trying to run "ai":
> 
> ![image](https://user-images.githubusercontent.com/130695190/238425791-295da564-5c42-44f8-ac8a-7af279934a13.png)

Should be fixed now, can you try it out when you have time?

**Comment by wonwoo0203** [comment] 2023-05-18 11:01
![image](https://github.com/Xvirus0/Xvirus-Tools/assets/124945199/23941e58-95c0-4c90-834b-56345758c16e)

I'm getting stuck here...
I'm on Windows 10 with Python 3.10.0

Also, why do my PC fans go crazy when I have the Xvirus command prompt window open?

**Comment by DXVVAY** [comment] 2023-05-18 11:58
Its not supposed to look like that thats the old version reinstall

**Comment by wonwoo0203** [comment] 2023-05-18 12:01
> Its not supposed to look like that thats the old version reinstall

This is the link right?
https://github.com/Xvirus0/Xvirus-Tools/releases/tag/1.5.8

**Comment by wonwoo0203** [comment] 2023-05-18 12:02
![image](https://github.com/Xvirus0/Xvirus-Tools/assets/124945199/08c6c080-6b73-4bc0-ba20-28975b40ce45)
Is this what its supposed to look like?

**Comment by Cwackz** [comment] 2023-05-18 13:25
> ![image](https://user-images.githubusercontent.com/124945199/239228055-08c6c080-6b73-4bc0-ba20-28975b40ce45.png) Is this what its supposed to look like?

Yep, its supposed to look like that, is there still a scraping issue?

**Comment by wonwoo0203** [comment] 2023-05-19 08:51
> > ![image](https://user-images.githubusercontent.com/124945199/239228055-08c6c080-6b73-4bc0-ba20-28975b40ce45.png) Is this what its supposed to look like?
> 
> Yep, its supposed to look like that, is there still a scraping issue?

Yes still stuck

**Comment by DXVVAY** [comment] 2023-05-19 11:49
yes

**Comment by Skyethebaka** [comment] 2023-05-29 23:26
![Screenshot_3](https://github.com/Xvirus0/Xvirus-Tools/assets/49079048/9462b796-2112-465b-8161-09e67b6da4a9)
I get these issues, it says stuck on scraping proxies and i get this error when running setup.bat (i have reinstalled the newest version like 4 times now and checked everything installed correctly)

**Comment by DXVVAY** [comment] 2023-05-30 06:34
Yes a iam aware of that problem i will fix it asap

**Comment by DXVVAY** [comment] 2023-06-01 17:02
> ![Screenshot_3](https://user-images.githubusercontent.com/49079048/241816717-9462b796-2112-465b-8161-09e67b6da4a9.png) I get these issues, it says stuck on scraping proxies and i get this error when running setup.bat (i have reinstalled the newest version like 4 times now and checked everything installed correctly)

this is an old version please update

**Comment by DXVVAY** [comment] 2023-06-02 08:52
another update is coming with paid proxies for free

**Closed by DXVVAY** 2023-06-02 08:52 UTC
Labels: bug, good first issue
